# Generated by Django 5.0.1 on 2024-02-02 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='url',
            field=models.URLField(max_length=2000),
        ),
    ]
